name: 'Vercel Deployment'
description: 'Deploys the project to Vercel using Vercel CLI'

inputs:
  vercel-token:
    required: true
  environment:
    required: false
    default: 'preview'

outputs:
  url:
    description: 'Deployment URL'
    value: ${{ steps.deploy.outputs.url }}

runs:
  using: 'composite'
  steps:
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
      shell: bash

    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=${{ inputs.environment }} --token=${{ inputs.vercel-token }}
      shell: bash

    - name: Build Project Artifacts
      run: |
        if [ "${{ inputs.environment }}" = "production" ]; then
          vercel build --prod --token=${{ inputs.vercel-token }}
        else
          vercel build --token=${{ inputs.vercel-token }}
        fi
      shell: bash

    - name: Deploy Project Artifacts to Vercel
      id: deploy
      run: |
        if [ "${{ inputs.environment }}" = "production" ]; then
          url=$(vercel deploy --prebuilt --prod --token=${{ inputs.vercel-token }})
        else
          url=$(vercel deploy --prebuilt --token=${{ inputs.vercel-token }})
        fi
        echo "url=$url" >> $GITHUB_OUTPUT
      shell: bash
